# Generated by Django 6.1 on 2026-09-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
