# Generated by Django 6.1 on 2026-09-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0002_userprofile_profile_setup_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='company_tag',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cgpa',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_target_role',
            field=models.CharField(blank=True, help_text='Custom target job role if not in list', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grade_type',
            field=models.CharField(choices=[('CGPA', 'CGPA (out of 10)'), ('Percentage', 'Percentage (%)')], default='CGPA', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='score_value',
            field=models.FloatField(default=8.0, help_text='CGPA value or Percentage value'),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='question_type',
            field=models.CharField(choices=[('HR', 'HR & Behavioral'), ('Technical', 'Technical Concept'), ('SQL', 'SQL & Queries'), ('Python', 'Python Coding'), ('Java', 'Java Programming'), ('Aptitude', 'Aptitude & Logical')], default='Technical', max_length=30),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(help_text='Detailed HTML study material'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('B.Sc Computer Science', 'B.Sc Computer Science'), ('B.Sc Information Technology', 'B.Sc Information Technology'), ('B.Sc Data Science', 'B.Sc Data Science'), ('B.Sc Computer Science with Artificial Intelligence', 'B.Sc Computer Science with Artificial Intelligence'), ('B.Sc Mathematics', 'B.Sc Mathematics'), ('B.Sc Physics', 'B.Sc Physics'), ('B.Sc Chemistry', 'B.Sc Chemistry'), ('B.Sc Biotechnology', 'B.Sc Biotechnology'), ('B.Sc Microbiology', 'B.Sc Microbiology'), ('B.Sc Psychology', 'B.Sc Psychology'), ('BCA', 'BCA (Bachelor of Computer Applications)'), ('B.Com General', 'B.Com General'), ('B.Com Computer Applications', 'B.Com Computer Applications'), ('B.Com Accounting & Finance', 'B.Com Accounting & Finance'), ('BBA', 'BBA (Bachelor of Business Administration)'), ('B.A English', 'B.A English'), ('B.A Tamil', 'B.A Tamil'), ('B.A Economics', 'B.A Economics'), ('B.A History', 'B.A History'), ('B.A Sociology', 'B.A Sociology'), ('B.A Visual Communication', 'B.A Visual Communication'), ('B.A Journalism', 'B.A Journalism')], default='B.Sc Computer Science', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills (e.g. Python, SQL, Accounting, Excel)'),
        ),
    ]
