# Generated by Django 6.1 on 2026-09-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0003_remove_interviewquestion_company_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='jobrole',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departments this role should be shown to', related_name='job_roles', to='placement_app.department'),
        ),
    ]
