# Generated by Django 6.1 on 2026-09-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0004_department_jobrole_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='department_group',
            field=models.CharField(choices=[('All', 'All Departments (Common)'), ('Computer/IT', 'Computer / IT (CS, IT, AI, DS, BCA)'), ('Science', 'Science (Maths, Physics, Chemistry, Bio, Micro, Psych)'), ('Commerce', 'Commerce / Management (B.Com, BBA)'), ('Arts', 'Arts (English, Tamil, Economics, History, Sociology, VisComm, Journalism)')], default='All', help_text='Which department stream sees this question in diagnostic quiz', max_length=20),
        ),
    ]
