# Generated by Django 6.1 on 2026-09-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0005_question_department_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='company_tag',
            field=models.CharField(blank=True, help_text='Company tag (e.g. TCS, Infosys, Zoho, Wipro)', max_length=100),
        ),
    ]
